CREATE TABLE [dbo].[Class]
(
	[ClassId] TINYINT NOT NULL,
	[Name] NVARCHAR(15) NOT NULL,
	[Armor] NVARCHAR (10) NOT NULL,
	[Type] NVARCHAR (15) NOT NULL
	CONSTRAINT [PK_Class] PRIMARY KEY CLUSTERED (ClassId)
)
